version: "3.9"
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    networks:
      - fast_network
  
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
    networks:
      - fast_network

networks:
  fast_network:
    name: fast_network